ktor:
  development: true
  application:
    modules:
      - dev.lmorita.ApplicationKt.module
  deployment:
    port: 8080

storage:
  driverClassName: "org.postgresql.Driver"
  jdbcURL: "jdbc:postgresql://db:5432/postgres"
  user: "postgres"
  password: "password"